### ISSUE TITLE
Loosing logs in Datadog output

### ISSUE THREAD

**Issue by walec51** [jd/daiquiri#46] opened 2020-09-01 14:52 UTC
I have a HTTP request that logs using `logger.info(...)` in three places (no ifs, three lines should always be logged)

I have a datadog output setup like this:

```
daiquiri.setup(
    outputs=[
        daiquiri.output.Datadog(
            hostname=os.environ["LOGGING_HOST"], port=int(os.environ["LOGGING_PORT"])
        ),
        daiquiri.output.Stream(sys.stdout),
    ],
    level=logging.INFO,
)
logger = daiquiri.getLogger(__name__)
``` 

the last `logger.info(...)` always makes it way do datadog

the first two sometimes do but most of the time don't

**Comment by walec51** [comment] 2020-09-01 15:10
tcp dump:

```
root@standard-pool-3rwpq:/# tcpdump -X -i cilium_host "tcp port 55302"
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode      
listening on cilium_host, link-type EN10MB (Ethernet), capture size 262144 bytes
15:08:12.137882 IP 10.244.1.117.33344 > 10.135.177.16.55302: Flags [P.], seq 3000443178:3000443350, ack 2841640562, win 221, options [nop,nop,TS val 3037970458
 ecr 1168862496], length 172
        0x0000:  4500 00e0 2219 4000 3f06 50ff 0af4 0175  E...".@.?.P....u
        0x0010:  0a87 b110 8240 d806 b2d7 212a a95f fe72  .....@....!*._.r
        0x0020:  8018 00dd c8d2 0000 0101 080a b513 c01a  ................
        0x0030:  45ab 6d20 7b22 6d65 7373 6167 6522 3a20  E.m.{"message":.
        0x0040:  2272 756e 6e69 6e67 2070 6173 735f 636c  "running.pass_cl
        0x0050:  6173 7369 6669 6572 5f6d 6f64 656c 222c  assifier_model",
        0x0060:  2022 7368 6f77 5f69 6422 3a20 3132 3735  ."show_id":.1275
        0x0070:  322c 2022 7665 6e75 655f 6964 223a 2032  2,."venue_id":.2
        0x0080:  3037 2c20 2274 696d 6573 7461 6d70 223a  07,."timestamp":
        0x0090:  2022 3230 3230 2d30 392d 3031 5431 353a  ."2020-09-01T15:
        0x00a0:  3038 3a31 322e 3133 3737 3835 222c 2022  08:12.137785",."
        0x00b0:  7374 6174 7573 223a 2022 696e 666f 222c  status":."info",
        0x00c0:  2022 6c6f 6767 6572 223a 207b 226e 616d  ."logger":.{"nam
        0x00d0:  6522 3a20 226d 6574 686f 6473 227d 7d0a  e":."methods"}}.
15:08:13.709402 IP 10.244.1.117.35618 > 10.135.177.16.55302: Flags [S], seq 3242891479, win 28200, options [mss 1410,sackOK,TS val 3037972030 ecr 0,nop,wscale 
7], length 0
        0x0000:  4500 003c 3bd9 4000 3f06 37e3 0af4 0175  E..<;.@.?.7....u
        0x0010:  0a87 b110 8b22 d806 c14a 98d7 0000 0000  ....."...J......
        0x0020:  a002 6e28 c82e 0000 0204 0582 0402 080a  ..n(............
        0x0030:  b513 c63e 0000 0000 0103 0307            ...>........
15:08:13.709513 IP 10.244.1.117.35618 > 10.135.177.16.55302: Flags [.], ack 3992912249, win 221, options [nop,nop,TS val 3037972030 ecr 1170277510], length 0  
        0x0000:  4500 0034 3bda 4000 3f06 37ea 0af4 0175  E..4;.@.?.7....u
        0x0010:  0a87 b110 8b22 d806 c14a 98d8 edff 0179  ....."...J.....y
        0x0020:  8010 00dd c826 0000 0101 080a b513 c63e  .....&.........>
        0x0030:  45c1 0486                                E...
15:08:13.709681 IP 10.244.1.117.35618 > 10.135.177.16.55302: Flags [P.], seq 0:159, ack 1, win 221, options [nop,nop,TS val 3037972030 ecr 1170277510], length 
159
        0x0000:  4500 00d3 3bdb 4000 3f06 374a 0af4 0175  E...;.@.?.7J...u
        0x0010:  0a87 b110 8b22 d806 c14a 98d8 edff 0179  ....."...J.....y
        0x0020:  8018 00dd c8c5 0000 0101 080a b513 c63e  ...............>
        0x0030:  45c1 0486 7b22 6d65 7373 6167 6522 3a20  E...{"message":.
        0x0040:  2249 6e63 7265 6173 696e 6720 6d61 7820  "Increasing.max.
        0x0050:  7072 6963 6522 2c20 226d 6178 5f70 7269  price",."max_pri
        0x0060:  6365 223a 2022 5b31 3130 2e31 3137 3332  ce":."[110.11732
        0x0070:  3636 365d 222c 2022 7469 6d65 7374 616d  666]",."timestam
        0x0080:  7022 3a20 2232 3032 302d 3039 2d30 3154  p":."2020-09-01T
        0x0090:  3135 3a30 383a 3133 2e37 3038 3836 3522  15:08:13.708865"
        0x00a0:  2c20 2273 7461 7475 7322 3a20 2269 6e66  ,."status":."inf
        0x00b0:  6f22 2c20 226c 6f67 6765 7222 3a20 7b22  o",."logger":.{"
        0x00c0:  6e61 6d65 223a 2022 6d65 7468 6f64 7322  name":."methods"
        0x00d0:  7d7d 0a                                  }}.
```

what was visible in datadog after this - just one entry:

![obraz](https://user-images.githubusercontent.com/738484/91869335-0efd5180-ec76-11ea-92e5-65091ff203bc.png)

**Comment by jd** [comment] 2020-09-01 15:44
I've no idea, pinging @sileht just in case he has a clue :)

**Comment by jd** [comment] 2020-09-01 15:45
Just to be clear, the `tcpdump` shows `running.pass_classifier_model` being sent, right?
If it's not in Datadog, it might be filtered out by the agent or the index on Datadog side itself?

**Comment by walec51** [comment] 2020-09-01 20:01
my logging code looks like this:

```
    // ...

    logger.info(
        "running pass_classifier_model",
        show_id=data["showId"],
        venue_id=data["venueId"],
    )

    // ...

    logger.info("Pass hit probability", model_proba=model_proba, data=data)

    // ...

    logger.info("Increasing max price", max_price=max_price)

    // ...
```

all those three lines get executed on each request

tcpdump sometime sees all three, sometime only the first and last one

here I have all three:

```
19:50:11.754155 IP 10.244.1.117.32856 > 10.135.177.16.55302: Flags [P.], seq 3475:3647, ack 1, win 221, options [nop,nop,TS val 3054889841 ecr 1187180574], len
gth 172
        0x0000:  4500 00e0 a548 4000 3f06 cdcf 0af4 0175  E....H@.?......u
        0x0010:  0a87 b110 8058 d806 1727 81ca 724b 7a56  .....X...'..rKzV
        0x0020:  8018 00dd c8d2 0000 0101 080a b615 eb71  ...............q
        0x0030:  46c2 f01e 7b22 6d65 7373 6167 6522 3a20  F...{"message":.
        0x0040:  2272 756e 6e69 6e67 2070 6173 735f 636c  "running.pass_cl
        0x0050:  6173 7369 6669 6572 5f6d 6f64 656c 222c  assifier_model",
        0x0060:  2022 7368 6f77 5f69 6422 3a20 3132 3735  ."show_id":.1275
        0x0070:  322c 2022 7665 6e75 655f 6964 223a 2032  2,."venue_id":.2
        0x0080:  3037 2c20 2274 696d 6573 7461 6d70 223a  07,."timestamp":
        0x0090:  2022 3230 3230 2d30 392d 3031 5431 393a  ."2020-09-01T19:
        0x00a0:  3530 3a31 312e 3735 3430 3530 222c 2022  50:11.754050",."
        0x00b0:  7374 6174 7573 223a 2022 696e 666f 222c  status":."info",
        0x00c0:  2022 6c6f 6767 6572 223a 207b 226e 616d  ."logger":.{"nam
        0x00d0:  6522 3a20 226d 6574 686f 6473 227d 7d0a  e":."methods"}}.
19:50:13.322913 IP 10.244.1.117.32856 > 10.135.177.16.55302: Flags [P.], seq 3647:4145, ack 1, win 221, options [nop,nop,TS val 3054891409 ecr 1187195321], len
gth 498
        0x0000:  4500 0226 a549 4000 3f06 cc88 0af4 0175  E..&.I@.?......u
        0x0010:  0a87 b110 8058 d806 1727 8276 724b 7a56  .....X...'.vrKzV
        0x0020:  8018 00dd ca18 0000 0101 080a b615 f191  ................
        0x0030:  46c3 29b9 7b22 6d65 7373 6167 6522 3a20  F.).{"message":.
        0x0040:  2250 6173 7320 6869 7420 7072 6f62 6162  "Pass.hit.probab
        0x0050:  696c 6974 7922 2c20 226d 6f64 656c 5f70  ility",."model_p
        0x0060:  726f 6261 223a 2022 5b30 2e39 3237 355d  roba":."[0.9275]
        0x0070:  222c 2022 6461 7461 223a 207b 2273 686f  ",."data":.{"sho
        0x0080:  7749 6422 3a20 3132 3735 322c 2022 7665  wId":.12752,."ve
        0x0090:  6e75 6549 6422 3a20 3230 372c 2022 6469  nueId":.207,."di
        0x00a0:  7370 6c61 7944 6174 6574 696d 6522 3a20  splayDatetime":.
        0x00b0:  2232 3032 302d 3037 2d32 3554 3139 3a33  "2020-07-25T19:3
        0x00c0:  303a 3030 2b30 323a 3030 222c 2022 7461  0:00+02:00",."ta
        0x00d0:  7269 6666 4261 7365 6c69 6e65 223a 207b  riffBaseline":.{
        0x00e0:  2273 7461 7274 4461 7465 7469 6d65 223a  "startDatetime":
        0x00f0:  2022 3230 3230 2d30 372d 3232 5431 393a  ."2020-07-22T19:
        0x0100:  3330 3a30 302b 3032 3a30 3022 2c20 2265  30:00+02:00",."e
        0x0110:  6e64 4461 7465 7469 6d65 223a 2022 3230  ndDatetime":."20
        0x0120:  3230 2d30 372d 3235 5431 383a 3330 3a30  20-07-25T18:30:0
        0x0130:  302b 3032 3a30 3022 2c20 2273 7461 7274  0+02:00",."start
        0x0140:  5072 6963 6522 3a20 3930 2e30 2c20 2265  Price":.90.0,."e
        0x0150:  6e64 5072 6963 6522 3a20 3635 2e30 7d2c  ndPrice":.65.0},
        0x0160:  2022 706c 6163 6553 616c 6553 7461 7473  ."placeSaleStats
        0x0170:  223a 205b 7b22 706c 6163 6554 7970 6522  ":.[{"placeType"
        0x0180:  3a20 2250 4153 5322 2c20 2273 6f6c 6450  :."PASS",."soldP
        0x0190:  6c61 6365 7322 3a20 3134 2c20 226e 6f74  laces":.14,."not
        0x01a0:  536f 6c64 506c 6163 6573 223a 2030 2c20  SoldPlaces":.0,.
        0x01b0:  2273 6361 6e6e 6564 506c 6163 6573 223a  "scannedPlaces":
        0x01c0:  206e 756c 6c7d 5d7d 2c20 2274 696d 6573  .null}]},."times
        0x01d0:  7461 6d70 223a 2022 3230 3230 2d30 392d  tamp":."2020-09-
        0x01e0:  3031 5431 393a 3530 3a31 332e 3332 3234  01T19:50:13.3224
        0x01f0:  3634 222c 2022 7374 6174 7573 223a 2022  64",."status":."
        0x0200:  696e 666f 222c 2022 6c6f 6767 6572 223a  info",."logger":
        0x0210:  207b 226e 616d 6522 3a20 226d 6574 686f  .{"name":."metho
        0x0220:  6473 227d 7d0a                           ds"}}.
19:50:13.323673 IP 10.244.1.117.32856 > 10.135.177.16.55302: Flags [P.], seq 4145:4304, ack 1, win 221, options [nop,nop,TS val 3054891410 ecr 1187196889], len
gth 159
        0x0000:  4500 00d3 a54a 4000 3f06 cdda 0af4 0175  E....J@.?......u
        0x0010:  0a87 b110 8058 d806 1727 8468 724b 7a56  .....X...'.hrKzV
        0x0020:  8018 00dd c8c5 0000 0101 080a b615 f192  ................
        0x0030:  46c3 2fd9 7b22 6d65 7373 6167 6522 3a20  F./.{"message":.
        0x0040:  2249 6e63 7265 6173 696e 6720 6d61 7820  "Increasing.max.
        0x0050:  7072 6963 6522 2c20 226d 6178 5f70 7269  price",."max_pri
        0x0060:  6365 223a 2022 5b31 3130 2e31 3137 3332  ce":."[110.11732
        0x0070:  3636 365d 222c 2022 7469 6d65 7374 616d  666]",."timestam
        0x0080:  7022 3a20 2232 3032 302d 3039 2d30 3154  p":."2020-09-01T
        0x0090:  3139 3a35 303a 3133 2e33 3233 3435 3422  19:50:13.323454"
        0x00a0:  2c20 2273 7461 7475 7322 3a20 2269 6e66  ,."status":."inf
        0x00b0:  6f22 2c20 226c 6f67 6765 7222 3a20 7b22  o",."logger":.{"
        0x00c0:  6e61 6d65 223a 2022 6d65 7468 6f64 7322  name":."methods"
        0x00d0:  7d7d 0a                                  }}.
19:50:28.337646 IP 10.244.1.117.32856 > 10.135.177.16.55302: Flags [.], ack 1, win 221, options [nop,nop,TS val 3054906424 ecr 1187196890], length 0
        0x0000:  4500 0034 a54b 4000 3f06 ce78 0af4 0175  E..4.K@.?..x...u
        0x0010:  0a87 b110 8058 d806 1727 8507 724b 7a56  .....X...'..rKzV
        0x0020:  8010 00dd c826 0000 0101 080a b616 2c38  .....&........,8
        0x0030:  46c3 2fda                                F./.
19:50:43.409685 IP 10.244.1.117.32856 > 10.135.177.16.55302: Flags [.], ack 1, win 221, options [nop,nop,TS val 3054921496 ecr 1187196890], length 0
        0x0000:  4500 0034 a54c 4000 3f06 ce77 0af4 0175  E..4.L@.?..w...u
        0x0010:  0a87 b110 8058 d806 1727 8507 724b 7a56  .....X...'..rKzV
        0x0020:  8010 00dd c826 0000 0101 080a b616 6718  .....&........g.
        0x0030:  46c3 2fda                                F./.
```

and all of them get noticed by datadog:

![obraz](https://user-images.githubusercontent.com/738484/91900188-98c11500-ec9e-11ea-8230-6434dec9abfa.png)

but in about 80% of the cases (like the one presented in my previous comment) I see only two messages in the dump and one in datadog

**Comment by walec51** [comment] 2020-09-01 20:03
ps. shouldn't there be a new line character at the end of each json object in a packet?

**Comment by walec51** [comment] 2020-09-01 20:19
I the same cluster I have an Java app that is integrated in a similar manner on a different port and it does no loose any messages.

**Comment by sileht** [comment] 2020-09-02 06:49
I didn't find the expected and exact data format. The documentation just says text or json.
Does your java app send "\n" between json ? it the lib to send data to datadog open-source (so I can take a look) ?

**Comment by walec51** [comment] 2020-09-02 08:39
here is what I'm using in my Java app:

```
    <appender name="DATADOG" class="net.logstash.logback.appender.LogstashTcpSocketAppender">
      <remoteHost>${DD_AGENT_HOST}</remoteHost>
      <port>${DD_LOGGING_PORT}</port>
      <keepAliveDuration>1 minute</keepAliveDuration>
      <encoder class="net.logstash.logback.encoder.LogstashEncoder" />
    </appender>

    <root level="INFO">
      <appender-ref ref="DATADOG" />
    </root>
```

I think that by default there is no new line added between JSONs:

https://github.com/logstash/logstash-logback-encoder/blob/dc8d0224d55ffb7d02ced507021ecabadb17da30/src/main/java/net/logstash/logback/composite/loggingevent/MessageJsonProvider.java#L68

**Comment by walec51** [comment] 2020-09-02 08:43
maybe this is some python TCP handling issue in a Kubernetes cluster like: https://github.com/kubernetes-client/python/issues/537

**Comment by walec51** [comment] 2020-10-01 12:46
I've noticed that I loose a message then the TCP flow changes

![obraz](https://user-images.githubusercontent.com/738484/94810856-e2fbfa00-03f4-11eb-95fc-8c6ab0ba54a3.png)

![obraz](https://user-images.githubusercontent.com/738484/94810869-e98a7180-03f4-11eb-86bd-e13d8b3e327b.png)

**Comment by walec51** [comment] 2020-10-08 12:44
We are doing a further analysis of this problem with the Datadog team.

Here's a new tcpflow - green line shows a missing message

![tcpflow](https://user-images.githubusercontent.com/738484/95459910-89577a80-0974-11eb-8708-6d7466792911.png)

Screenshot from datadog - green arrow shows where the missing message should be

![datadog](https://user-images.githubusercontent.com/738484/95459903-865c8a00-0974-11eb-8c1d-412b7bc3d97e.png)

in the time the massage is missing in the Datadogs agent we can find:

`2020-10-08 12:14:08 UTC | CORE | WARN | (pkg/logs/input/listener/tailer.go:88 in readForever) | Couldn't read message from connection: read tcp 10.135.177.18:55302->10.244.0.238:57668: i/o timeout`

**Comment by jd** [comment] 2020-10-08 12:56
That's interesting. For what it's worth we've been using that Datadog output from daiquiri for a while without issue, but our agent runs on `localhost`.

If that can help, daiquiri leverages Python logging [`SocketHandler`](https://docs.python.org/3/library/logging.handlers.html#sockethandler) class that sends data over TCP.

I don't think daiquiri (nor Python) do anything fancy here. It's possible the connection is cut for whatever reason and the retry code in the Python logging module is not so good. Looking at the code, if a call to `sendall` fails, it reconnects but do not retry to resend. That might be the root cause of the issue in your case.

Did you try running Datadog agent on localhost by any chance, to avoid the network issue?

**Comment by jd** [comment] 2020-11-07 09:27
@walec51 we hit a similar problem recently and we tried switching to UDP rather than TCP. I just released daiquiri 3.0.0 that adds support for UDP.
You can use
```
daiquiri.output.Datadog(
                handler_class=daiquiri.handlers.PlainTextDatagramHandler
            )
```
To use UDP instead of TCP (don't forget to configure your agent to listen to UDP.

That might be worth a try.

**Comment by walec51** [comment] 2020-11-16 13:29
@jd thanks for the info - I'll try it

earlier I've tried to help support at Datadog to fix TCP support in their agent but after a dozen of mails they ware unhelpful and ignored the issue

**Comment by jd** [comment] 2020-11-16 15:59
I don't know what's wrong with TCP honestly. I've asked them to add support for Unix Domain Socket instead, they support it for e.g. traces and it'd be better to use that when the agent runs on the same host.

In our case, using UDP solved the issue and we're not losing any log anymore.

**Comment by walec51** [comment] 2021-03-10 20:33
we have switched to UDP and its been working great for 3 months now

thank you for adding this protocol to your library

**Comment by jd** [comment] 2021-03-11 16:59
Awesome! Thanks for getting back to me. I'll close this.

**Closed by jd** 2021-03-11 16:59 UTC
